CREATE TABLE IF NOT EXISTS Equipes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nomeFazenda TEXT,
  numeroDaEquipe INTEGER
);

CREATE TABLE IF NOT EXISTS Categorias (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT
);

CREATE TABLE IF NOT EXISTS NumeroDeLargadas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  numeroDeLargada INTEGER
);
CREATE TABLE IF NOT EXISTS Lacador(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT,
  classe TEXT,
  irmao TEXT,
  categorias TEXT
); 